<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton_login</name>
   <tag></tag>
   <elementGuidId>e59c5cfc-68ab-4af0-93e8-449c6a14d829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;btn-login&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btn-login&quot;]</value>
      <webElementGuid>82f6f28d-e6a4-49a0-b977-0625439eba71</webElementGuid>
   </webElementProperties>
</WebElementEntity>
