<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton_entrar</name>
   <tag></tag>
   <elementGuidId>d73bc457-27e1-4aa7-83d1-70ad5d3cd1c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id=&quot;btn-make-appointment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id=&quot;btn-make-appointment&quot;]</value>
      <webElementGuid>8458cc58-f016-472d-8869-9024121644ba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
