<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>calendar_input</name>
   <tag></tag>
   <elementGuidId>c874b8f2-5cb4-4896-8a24-54f996739ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;txt_visit_date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txt_visit_date&quot;]</value>
      <webElementGuid>443f29b3-df7f-4e65-bca5-3c41456b0693</webElementGuid>
   </webElementProperties>
</WebElementEntity>
